# Generated by Django 2.0.6 on 2018-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('is_favorite', models.BooleanField(default=False)),
                ('file_format', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
