# Generated by Django 2.0.6 on 2018-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='username',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
