# Generated by Django 2.0.6 on 2018-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0004_auto_20180715_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
