# Generated by Django 2.0.7 on 2018-07-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0005_auto_20180715_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_uploader',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
